name = "Shwchurch"
license = "MIT"
description = "Hugo theme for Beijing Shouwang Church"
homepage = "https://github.com/shwchurch3/hugo-theme-shwchurch"
tags = ["blog", "responsive", "highlight", "clean"]
features = ["blog", "responsive", "highlight", "clean"]
min_version = "0.1"

[author]
  name = "Shwchurch"
  homepage = "https://github.com/shwchurch3/hugo-theme-shwchurch"


